DIRECTION_FORWARD = 'F'
DIRECTION_FORWARD_RIGHT = 'FR'
DIRECTION_FORWARD_LEFT = 'FL'
DIRECTION_REVERSE = 'Rv'
DIRECTION_REVERSE_RIGHT = 'RvR'
DIRECTION_REVERSE_LEFT = 'RvL'
DIRECTION_RIGHT = 'R'
DIRECTION_LEFT = 'L'
DIRECTION_NONE = 'S'

TARGET_ACTION_FORWARD = 'F'
TARGET_ACTION_REVERSE = 'Rv'
TARGET_ACTION_LEFT = 'L'
TARGET_ACTION_RIGHT = 'R'

SPEED_INCREMENT = 10
