#!/usr/bin/env bash

shopt -s expand_aliases

export DEBIAN_FRONTEND=noninteractive

export RASPBERRYBOT_ROOT=/opt/raspberry-bot
export SUPERVISOR_ROOT=$RASPBERRYBOT_ROOT/supervisor
export API_SERVER_ROOT=$RASPBERRYBOT_ROOT/api
export WEB_INTERFACE_ROOT=$RASPBERRYBOT_ROOT/web

export PYTHONPATH="$RASPBERRYBOT_ROOT/src:$PYTHONPATH"

# [ -f "/opt/ros/melodic/setup.bash" ] && sudo /opt/ros/melodic/setup.bash
export TURTLEBOT3_MODEL=waffle_pi
